config/routes.rb
  Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:new, :create, :edit, :update, :destroy]

  resources :cars, only: [:index, :show, :new, :create, :destroy] do
  resources :reservations
  end

  root 'welcome#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :owner
  belongs_to :category
  has_many :reservations, dependent: :destroy
  has_many :ratings, through: :reservations
  geocoded_by :pickup_address
  after_validation :geocode, if: :pickup_address_changed?
  has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
  validates :seats, numericality: { greater_than: 0 }
  validates :category_id, presence: true
  validates :rate, presence: true, numericality: true
  validates :pickup_address, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :cars
  validates :name, presence: true, uniqueness: true
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  belongs_to :user
  has_many :cars
end

app/models/renter.rb
class Renter < ActiveRecord::Base
  belongs_to :user
  has_many :reservations
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :renter
  belongs_to :car
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, omniauth_providers: [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :owner
  belongs_to :renter

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :find_car, only: [:show, :destroy]

  def index
    if params[:pickup_address].present?
      @cars = Car.near(params[:pickup_address], 500)
    #if params[:search]
      #@cars = Car.where(pickup_address: params[:search])
    else
      @cars = Car.all
    end

    @markers = Gmaps4rails.build_markers(@cars[0..9]) do | car, marker |
     marker.lat car.latitude
     marker.lng car.longitude
    end

  end

  def show
    @car = Car.find(params[:id])
    @car_coordinates = { lat: @car.latitude, lng: @car.longitude }
end


  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def destroy
    @car.destroy
    redirect_to cars_path
  end

  private

  def car_params
    params.require(:car).permit(:pickup_address, :year, :mileage, :fuel, :seats, :rate, :category_id, :picture)
  end

  def find_car
   @car = Car.find(params[:id])
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :find_car

  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def create
    if user_signed_in?
      @reservation = @car.reservations.build(reservation_params)
        if @reservation.save
          redirect_to car_reservations_path, notice: "Your reservation has been successful"
        else
          render :new
        end
    else
      redirect_to cars_path, notice: "You have to be signed in to make a reservation"
    end
  end

  def destroy
    @reservation = @car.reservations.find(params[:id])
    @reservation.destroy
    redirect_to car_path(@car), notice: "Your reservation has been deleted"
  end

  private

  def find_car
    @car = Car.find(params[:car_id])
  end

  def reservation_params
    params.require(:reservation).permit(:checkin, :checkout, :rating, :car_id)
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])
    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to cars_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
    if @user.save
      redirect_to cars_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to cars_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cars/_map_box.html.erb
<div class="map_box">
  <h3><%= car.pickup_address %></h3>
  <%= link_to "Car details", new_car_reservation_path(car), class: "btn btn-warning" %>
</div>

app/views/cars/create.html.erb
<h1>Cars create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/destroy.html.erb
<h1>Cars destroy</h1>
<p>Find me in app/views/cars/destroy.html.erb</p>

app/views/cars/edit.html.erb
<h1>Cars edit</h1>
<p>Find me in app/views/cars/edit.html.erb</p>

app/views/cars/index.html.erb
<div class="container">
  <div class="row text-center">
    <h1>Awesome cars around you</h1>
    <div class="col-xs-12 col-md-6 text-center">
      <% @cars.each do | car | %>
          <div class="col-sm-6 col-md-6 xs-padded">
            <div class="thumbnail">
              <div class="caption">
                  <% if car.picture.present? %>
                <p><%= image_tag car.picture.url(:thumb) %></p>
              <% else %>
                <p><%= image_tag ("aircnc.jpg"), height: '65', width: '100' %></p>
              <% end %>
                <p><%= "#{car.pickup_address}" %></p>
                  <p><span class="label label-info price-label"><%= car.rate %> €</span></p>
                  <p>
                   Ratings:
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star"></i>
                  <i class="fa fa-star-o"></i>
                  (1492)
                </p>
                <p class="text-center">
                  <%= link_to("Show car details", car_path(car), class: "btn btn-default btn-sm", role: "button") %>
                </p>
              </div>
            </div>
          </div>
      <% end %>
    </div>


    <div class="col-xs-12 col-md-6 xs-padded">
      <!-- placeholder for the map -->
      <div id="map" class="thumbnail" style="width: 100%; height: 600px;"></div>
    </div
>  </div>
</div>

<% content_for(:after_js) do %>
 <%= javascript_tag do %>
   $(document).on('ready', function() {
     handler = Gmaps.build('Google');
     handler.buildMap({ internal: { id: 'map' } }, function(){
       markers = handler.addMarkers(<%= raw @markers.to_json %>);
       handler.bounds.extendWith(markers);
       handler.fitMapToBounds();
     });
   })
 <% end %>
<% end %>

app/views/cars/new.html.erb
<h1 class="text-center">Car listing form</h1>

<%= simple_form_for @car do |f| %>
  <%= f.error_notification %>

  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 text-left">
      <div class="card-block shadowed-box text-center">
        <div class= "sizee"
          <div class="form-inputs">
    <%= f.input :pickup_address %>
    <%= f.association :category %>
    <%= f.input :year, as: :date, discard_day: true, discard_month: true %>
    <%= f.input :mileage %>
    <%= f.input :fuel, as: :select, collection: ['petrol', 'diesel', 'hybrid', 'electric'] %>
    <%= f.input :seats, input_html: { min: 0 } %>
    <%= f.input :rate, label:"Price/day" %>
    <%= f.input :picture %>
  </div>
</div>
 </div>
</div>
<div class ="sizee">
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
</div>
<% end %>

app/views/cars/show.html.erb
<div class="row">
<div class="container text-center">
  <h1>Car details</h1>
    <h3><em>Here is the car you are looking for :</em></h3>

<strong>City:</strong> <%= @car.pickup_address %><br>
<strong>Category:</strong> <%= @car.category.name %><br>
<strong>Year:</strong> <%= @car.year %><br>
<strong>Mileage:</strong> <%= @car.mileage %><br>
<strong>Number of seats:</strong> <%= @car.seats %><br>
<strong>Price per day:</strong> <%= @car.rate %><br>
<%= image_tag @car.picture.url(:medium) %><br>

<%= link_to 'Reserve this car', new_car_reservation_path(@car), class: "btn btn-primary" %>
<%= link_to 'Back to search results', cars_path, class: "btn btn-primary" %>

</div>
</div>

app/views/cars/update.html.erb
<h1>Cars#update</h1>
<p>Find me in app/views/cars/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>AirCnC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Cookie" %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

</head>

<body>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1475178039453629',
      xfbml      : true,
      version    : 'v2.4'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

</script>

  <%= render "shared/navbar" %>
  <%= render 'shared/notices' %>
  <%= render 'shared/alerts' %>

  <%= yield %>

  <%= render "shared/footer" %>

  <script src="//maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
  <script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyAvK-eEW-W5dVZWEUCkqnfBqv-AKFDL6UY">
</script>
   <script type="text/javascript" src="autocomplete.js"></script>
  <%= javascript_include_tag "application" %>


  <%= yield(:after_js) %>
</body>
</html>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/index.html.erb
<h1>Reservations</h1>

<ul>
  <% @car.reservations.each do |reservation| %>
    <li><strong>Checkin:</strong> <%= reservation.checkin %></li>
    <li><strong>Checkout:</strong> <%= reservation.checkout %></li>
    <li><strong>City:</strong> <%= @car.pickup_address %></li>
    <li><strong>Category:</strong> <%= @car.category.name %></li>
    <li><strong>Year:</strong> <%= @car.year %></li>
    <li><strong>Mileage:</strong> <%= @car.mileage %></li>
    <li><strong>Number of seats:</strong> <%= @car.seats %></li>
    <%= image_tag @car.picture.url(:medium) %><br>
  <% end %>
</ul>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= simple_form_for ([@car, @reservation]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :checkin %>
    <%= f.input :checkout %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reservations/show.html.erb
<h1>Reservation details</h1>

<ul>
    <li><strong>Checkin:</strong> <%= @reservation.checkin %></li>
    <li><strong>Checkout:</strong> <%= @reservation.checkout %></li>
    <li><strong>City:</strong> <%= @car.city %></li>
    <li><strong>Category:</strong> <%= @car.category.name %></li>
    <li><strong>Year:</strong> <%= @car.year %></li>
    <li><strong>Mileage:</strong> <%= @car.mileage %></li>
    <li><strong>Number of seats:</strong> <%= @car.seats %></li>
<%= image_tag @car.picture.url(:medium) %><br><br><br>
<%= link_to 'Delete this reservation', car_reservation_path(@car, @reservation), class: "btn btn-primary", method: :delete, data: {confirm: "Are you positive that you want to delete this reservation?"}  %> <%= link_to 'Back to search results', cars_path, class: "btn btn-primary" %><br>
  </ul>

app/views/shared/_alerts.html.erb
<% if alert %>
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-distributed">

  <div class="footer-left">

    <h3>Air<span>CnC</span></h3>

    <p class="footer-links">
      <a href="#">Home</a>
    </p>

    <p class="footer-company-name">AirCnC &copy; 2015</p>
  </div>

  <div class="footer-center">

    <div>
      <i class="fa fa-map-marker"></i>
      <p><span>21 Baker Street</span> London, UK</p>
    </div>

    <div>
      <i class="fa fa-phone"></i>
      <p>+1 555 123456</p>
    </div>

    <div>
      <i class="fa fa-envelope"></i>
      <p><a href="mailto:support@aircnc.com">support@aircnc.com</a></p>
    </div>

  </div>

  <div class="footer-right">

    <p class="footer-company-about">
      <span>About the company</span>
      Courage & Passion are the keys of success at Air CnC
    </p>

    <div class="footer-icons">

      <a href="#"><i class="fa fa-facebook"></i></a>
      <a href="#"><i class="fa fa-twitter"></i></a>
      <a href="#"><i class="fa fa-linkedin"></i></a>
      <a href="#"><i class="fa fa-github"></i></a>

    </div>

  </div>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">
    <a href="/" id= "logo-car">
          <%= image_tag "aircnc.jpg", id: "logo-car" %>
    </a>

    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search for featured stuff">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
    <hr>
    <% if user_signed_in? %>
      <%= link_to t(".top_call_to_action", default: "List my car!"), new_car_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>

      <% end %>
      <hr>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Click and Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
</nav>

app/views/shared/_notices.html.erb
<% if notice %>
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <div class="alert alert-info alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/index.html.erb
<header id="top" class="header">

    <div class="text-vertical-center">
        <h1>Welcome to Air CnC</h1>
        <h3><em>"Drive as if you were at home"</em></h3>
        <br>
        <a href="#about" class="btn btn-dark btn-lg">Get a car</a>
    </div>
</header>

<!-- About -->
<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>
<section id="about" class="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>Search from the list of our best cars</h2>
       <div class="search">
        <div class="container">
          <div class="row">
            <div class="col-md-10 col-md-offset-1">
              <div class="form-section">
                <div class="row">
                  <form role="form" action="<%= cars_path %>">
                      <div class="col-md-2">
                        <div class="form-group">
                          <label class="sr-only" for="location">Location</label>
                          <input type="text" class="form-control" id="user_input_autocomplete_address" placeholder="From where ?" name="pickup_address">
                        </div>
                      </div>
                      <div class="col-md-2">
                        <div class="form-group">
                        <div class='input-group date' id='datetimepicker1'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                    </div>
                   </div>
                    </div>
                      <div class="col-md-2">
                        <div class="form-group">
                        <div class='input-group date' id='datetimepicker2'>
                    <input type='text' class="form-control" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                    </div>
                   </div>
                    </div>

                        <div class="col-md-2">
                        <div class="form-group">
                          <label class="sr-only" for="Car_category">Car Category</label>
                          <select id="Car_category" name="Category" class="form-control">
                              <option value="1">Cars from Movies</option>
                              <option value="2">Vintage cars</option>
                              <option value="3">Day to day cars</option>
                              <option value="4">Family Cars</option>
                              <option value="5">Minivans</option>
                              <option value="6">Supercars</option>
                          </select>
                        </div>
                      </div>
                      <div class="col-md-2">
                        <div class="form-group">
                          <label class="sr-only" for="guest">Guest</label>
                          <select id="seats" name="seats" class="form-control">
                              <option value="1">1 seat</option>
                              <option value="2">2 seats</option>
                              <option value="3">3 seats</option>
                              <option value="4">4 seats</option>
                              <option value="5">5 seats</option>
                              <option value="6">6 seats</option>
                              <option value="7">7 seats</option>
                              <option value="8">8 seats</option>
                          </select>
                        </div>
                      </div>
                      <div class="col-md-2">
                        <button type="submit" class="btn btn-default btn-primary">Search</button>
                      </div>
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
<br>
<br>
<div class="bg-white">
  <div class="container">
    <div class="row">
 <div class="col-xs-12 col-md-4">
    <h3>Cars from Movies</h3>
          <td><img src="//www.picamon.com/wp-content/uploads/2015/02/Cars-animation-movie-backgrounds-hd-8.png"width ="150px"></td>
    </div>

<div class="col-xs-12 col-md-4">
    <h3>Vintage Cars </h3>
        <td><img src="//m2.behance.net/rendition/pm/12192295/disp/aaa0987fa1b03df9adb03f06baa81814.jpg"width = "150" px></td>
        </td>
      </div>

<div class="col-xs-12 col-md-4">
    <h3>Day to Day Cars </h3>
        <td><img src="//images.all-free-download.com/images/graphiclarge/fiat_car_vector_38651.jpg"width = "150" px></td>
      </div>
    </div>

<div class="row">
<div class="col-xs-12 col-md-4">
    <h3>Family Cars </h3>
        <td><img src="//www.utmostcars.com/wp-content/uploads/2013/06/Good-Family-Car.jpg"width = "150" px></td>
      </div>


<div class="col-xs-12 col-md-4">
    <h3>Minivans </h3>
        <td><img src="//www.rfmrentalcars.co.nz/wp-content/themes/blue-zinfandel-enhanced-20/images/toyota-hiace-for-lease.jpg"width = "150" px></td>
      </div>

<div class="col-xs-12 col-md-4">
    <h3>Supercars </h3>
        <td><img src="//www.hdicon.com/wp-content/uploads/2011/04/vector-car.jpg"width = "150" px></td>
      </div>


    </div>
  </div>
</div>

            </div>

        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</section>


    <!-- /.container -->
</section>

  <script>
  $(document).ready(function(){
    $('body').addClass('main-page');
  })
  </script>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(function () {
                $('#datetimepicker1').datetimepicker();
    });
    $(function () {
                $('#datetimepicker2').datetimepicker();
    });
  <% end %>

<% end %>